import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import Footer from '../components/footer'
import dynamic from 'next/dynamic'
import Link from 'next/link'

const CatalogCompo = dynamic(() => import("shop/catalog"),{ssr: false})

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav>This is navbar main app</Nav>

        Welcome to Main app port:3000
        <Link href={"/catalogOnMain"}>Go to catalog</Link>
        catalog from shop
        <CatalogCompo />
        <Footer></Footer>
      </main>
    </>
  )
}
